-- AlterTable
ALTER TABLE `conversation` ADD COLUMN `cost` DECIMAL(65, 30) NOT NULL DEFAULT 0.0,
    ADD COLUMN `count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `version` INTEGER NOT NULL DEFAULT 1;
